### ISSUE TITLE
[REQUEST] does this support auth header?

### ISSUE THREAD

**Issue by hannojg** [zhigang1992/react-native-video-cache#12]
Hey, I was wondering whether we can attach the header to the URI, for example an authentication header. This is quite common when accessing media resources in mobile applicaitons.

**Comment by zhigang1992** [comment]
You have to look for it in 

iOS: https://github.com/ChangbaDevs/KTVHTTPCache
Android: https://github.com/danikula/AndroidVideoCache

This repo is just a wrapper for these two libraries.

**Comment by kamranaashiq** [comment]
@hannojg Hi, did you find any solution?
