### ISSUE TITLE
The Video URL doesn't change on Android Release mode

### ISSUE THREAD

**Issue by haThaiHoang** [zhigang1992/react-native-video-cache#14]
Please help me with this issue. I have use react-native 0.63

**Comment by zhigang1992** [comment]
What do you mean it doesn't change? input and output is the same?

**Comment by haThaiHoang** [comment]
@zhigang1992 Yes, it is.
I just fixed it by add `android:usesCleartextTraffic="true"` to AndroidManifest.xml 
Thank you

**Comment by Subiyel** [comment]
`convertToProxyURL(url)` returns same value as of original url. Is this expected behaviour? 
i'm am also using `android:usesCleartextTraffic="true"`

**Comment by zhigang1992** [comment]
If you're using chrome debugging, then it will return the same URL.
