### ISSUE TITLE
error: incompatible types: unexpected return value

### ISSUE THREAD

**Issue by gibrandev** [zhigang1992/react-native-video-cache#19]
We have error in version 2.0.1, here detail error.
```console
react-native-video-cache\android\src\main\java\com\reactnative\videocache\VideoCacheModule.java:29: error: incompatible types: unexpected return value
        return this.proxy.getProxyUrl(url);
                                     ^
```

**Comment by zhigang1992** [comment]
Ah. Sry about that.

The type signature on that Java method need to be updated to return a string. 

I can get to that tonight, or you can patch package it for now.

**Comment by gibrandev** [comment]
thank you for the reply. I'll be waiting for this moment.

**Comment by zhigang1992** [comment]
You can revert back to 1.* as well. But that uses async Bridge that has its own problems

**Comment by gibrandev** [comment]
Of course, I got this error after upgrading. I'm currently using version 1 and canceled the upgrade

**Comment by zhigang1992** [comment]
I've pushed 2.0.2, should fixed the issue. I'm still testing

Note that v1 -> v2 is breaking change.

Since you now no longer need to await the convert call.

**Comment by gibrandev** [comment]
Thanks, this is work now.
