### ISSUE TITLE
Link issue in IOS

### ISSUE THREAD

**Issue by pitchourou** [zhigang1992/react-native-video-cache#3]
getting RNVideoCache is undefined.
i see no RNVideoCache.xcodeproj , seems the libray cannot be linked

**Comment by zhigang1992** [comment]
I've just released 1.0.0 which support legacy `.xcodeproj` linking. This project was previously only built for linking with `CocoaPods`, if you do link with `.xcodeproj`, please remeber to add `KTVHTTPCache` to your project manually.
