### ISSUE TITLE
Require Functionality Explanation

### ISSUE THREAD

**Issue by naeemqaswar** [zhigang1992/react-native-video-cache#4]
I have implemented your plugin for online videos which are loaded in a player (react-native-video). Function "convertToProxyURL()" is returning a URL starting with http://127.0.0.1:57688/... sounds like its working. But i don't see any significant difference in loading time or any performance increase in overall app. Can you please explain how things are working at backend and how can i get most of it?

**Comment by zhigang1992** [comment]
You can find more detail here

https://github.com/ChangbaDevs/KTVHTTPCache

**Comment by naeemqaswar** [comment]
Thanks, its Flow Chart explained everything.
