### ISSUE TITLE
RN 0.65 Android Build fails due to jcenter deprecation

### ISSUE THREAD

**Issue by Yonom** [zhigang1992/react-native-video-cache#41]
Since RN 0.65, Jcenter is no longer used by react native and mavenCentral is used instead. This causes the android build to fail because com.danikula:videocache is not available in mavenCentral

  > Could not find com.danikula:videocache:2.7.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - file:/Users/yonom/.m2/repository/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - file:/Users/yonom/GitHub/read-o/app/node_modules/react-native/android/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - file:/Users/yonom/GitHub/read-o/app/node_modules/jsc-android/dist/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://dl.google.com/dl/android/maven2/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - https://www.jitpack.io/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
       - file:/Users/yonom/GitHub/read-o/app/node_modules/expo-camera/android/maven/com/danikula/videocache/2.7.1/videocache-2.7.1.pom
     Required by:
         project :app > project :react-native-video-cache

**Comment by missstaff** [comment]
> I would advice to define the package so other dependencies are not fetched/taken from jCenter anymore. Because jCenter does not allow any updates anymore of any package all other packages should be taken from mavenCentral for example.
> 
> You can add jcenter to android/build.gradle like this:
> 
> ```
> allprojects {
>     repositories {
>         .... # Keep the rest
>         jcenter() {
>             content {
>                includeModule("com.danikula", "videocache")
>             }
>         }
>     }
> }
> ```
> 
> Hopefully somebody updates videocache to use another repository

this was the solution I needed thank you

**Comment by ChiKaLiO** [comment]
why do i keep getting back to this issue  is there no update no fix ?
