### ISSUE TITLE
what is the maxmimum cache size and the expiration time for the cache?

### ISSUE THREAD

**Issue by bumpingChris** [zhigang1992/react-native-video-cache#6]
Does the resulting file from "convertToProxyURL" expire and what is the maximum size of the cache?

Thanks

**Comment by zhigang1992** [comment]
Please ref to native libraries.

iOS: https://github.com/ChangbaDevs/KTVHTTPCache
Android: https://github.com/danikula/AndroidVideoCache

**Comment by zhigang1992** [comment]
In general we should call the function on every app launch.

The cache size only subject to the device available disk
