### ISSUE TITLE
Cannot read property 'convert' of undefined

### ISSUE THREAD

**Issue by crushy26** [zhigang1992/react-native-video-cache#7]
Hi, 

Thank you for open sourcing this library. I was looking for a good video cache solution for RN.

I have successfully linked this library, but as soon app starts, it throws an error saying, 'Cannot read property 'convert' of undefined' in Index.js:5

React native: 0.59.10
Device: one plus 3
Android: 9

**Comment by crushy26** [comment]
Hi @zhigang1992 any update on this? Please help.

**Comment by zhigang1992** [comment]
Can you share a reproduce repo? There is a example project which should be running fine

**Comment by crushy26** [comment]
Seems like it was an issue from my end. I added videocache in getpackages and it's working fine now.

One question: does this package download everything at once and then caches it or it downloads as a stream so that video can continue to play?

**Comment by zhigang1992** [comment]
the later

**Comment by crushy26** [comment]
Okay, thanks
